#!/bin/bash
udev_install_dir="/etc/udev/rules.d"
udev_file_source="$(dirname $0)"

cp $udev_file_source/80-link.rules $udev_install_dir

# Load module at boot
cp $udev_file_source/inmos-link.conf /etc/modules-load.d
